### ISSUE TITLE
New comment on https://yanirseroussi.com/2022/03/20/building-useful-machine-learning-tools-keeps-getting-easier-a-fish-id-case-study/

### ISSUE THREAD

**Issue by beatboxerish** [yanirs/yanirseroussi.com#5]
Loved this short blog. Planning to transition to Climate tech as a DS guy and am slowly cultivating a pent-up passion for conserving the marine life so too many things that I can relate to here haha

**Comment by yanirs** [comment]
Thank you! Good luck with the transition. :slightly_smiling_face:
